# Generated by Django 4.2 on 2023-04-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='no_picture.jpeg', upload_to='products'),
        ),
    ]
